// // import type { Metadata } from "next";
// // import "./globals.css";
// // import { Footer } from "@/components/layout/Footer";
// // import { LanguageProvider } from "./context/LanguageContext";

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body>
// //         <LanguageProvider>
// //           {children}
// //           <Footer />
// //         </LanguageProvider>
// //       </body>
// //     </html>
// //   );
// // }
// import type { Metadata } from "next";
// import "./globals.css";
// import { Footer } from "@/components/layout/Footer";
// import { LanguageProvider } from "./context/LanguageContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `
//               (function() {
//                 try {
//                   const saved = localStorage.getItem('theme');
//                   const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
//                   if (saved === 'dark' || (!saved && prefersDark)) {
//                     document.documentElement.classList.add('dark');
//                   }
//                 } catch(e) {}
//               })();
//             `,
//           }}
//         />
//       </head>
//       <body>
//         <LanguageProvider>
//           {children}
//           <Footer />
//         </LanguageProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/layout/Footer";
import { LanguageProvider } from "./context/LanguageContext";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <LanguageProvider>
            {children}
            <Footer />
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
